import { CveEntry } from "./types";

// Curated set of publicly disclosed CVEs and bugs credited to AI assistance.
// Sourced from vendor advisories, Anthropic Red, Mozilla MFSA, FreeBSD-SA, Google
// Project Zero notes, Calif disclosure, SecurityWeek, Schneier, The Register, CSO.
// Verified data only - lower-confidence items live in lib/aggregate.ts.
export const CVES: CveEntry[] = [
  {
    id: "CVE-2026-4747",
    vendor: "FreeBSD",
    product: "FreeBSD kernel",
    component: "rpc.rpcsec_gss / NFS server",
    vulnType: "Stack buffer overflow (RCE, unauth)",
    severity: "critical",
    cvss: 9.8,
    discoveryMethod: "mythos",
    discoveryCredit: "Nicholas Carlini using Claude (Anthropic)",
    disclosedAt: "2026-03-26",
    patchedAt: "2026-03-26",
    ageYears: 17,
    glasswingPartner: undefined,
    patchStatus: "patched",
    summary:
      "svc_rpc_gss_validate copied an attacker-controlled credential body into a 128-byte stack buffer without bounds checking. Mythos chained a 20-gadget ROP split across packets for unauth remote root on the NFS server. Present since 2008.",
    source: { label: "FreeBSD-SA-26:08.rpcsec_gss", url: "https://www.freebsd.org/security/advisories/" },
  },
  {
    id: "CVE-2026-6746",
    vendor: "Mozilla",
    product: "Firefox 150",
    component: "WebRTC / DOM",
    vulnType: "Use-after-free",
    severity: "high",
    discoveryMethod: "mythos",
    discoveryCredit: "Evyatar Ben Asher, Keane Lucas, Nicholas Carlini et al using Claude (Anthropic)",
    disclosedAt: "2026-04-21",
    patchedAt: "2026-04-21",
    glasswingPartner: undefined,
    patchStatus: "patched",
    summary:
      "Use-after-free in the DOM, credited explicitly to Claude in MFSA 2026-30. One of three Mythos finds in Firefox 150 that crossed the public CVE threshold. The other 268 issues from the same evaluation pass shipped as defense-in-depth fixes.",
    source: { label: "MFSA 2026-30", url: "https://www.mozilla.org/en-US/security/advisories/" },
  },
  {
    id: "CVE-2026-6757",
    vendor: "Mozilla",
    product: "Firefox 150",
    component: "WebAssembly / SpiderMonkey",
    vulnType: "Use-after-free (invalid pointer)",
    severity: "high",
    discoveryMethod: "mythos",
    discoveryCredit: "Anthropic Mythos research",
    disclosedAt: "2026-04-21",
    patchedAt: "2026-04-21",
    glasswingPartner: undefined,
    patchStatus: "patched",
    summary:
      "Invalid-pointer use-after-free in the JavaScript WebAssembly component. Reachable from web content, fixed in 150 alongside 40 other public CVEs in the same advisory.",
    source: { label: "Red Hat CVE-2026-6757", url: "https://access.redhat.com/security/cve/cve-2026-6757" },
  },
  {
    id: "CVE-2026-6758",
    vendor: "Mozilla",
    product: "Firefox 150",
    vulnType: "Use-after-free",
    severity: "high",
    discoveryMethod: "mythos",
    discoveryCredit: "Anthropic Mythos research",
    disclosedAt: "2026-04-21",
    patchedAt: "2026-04-21",
    glasswingPartner: undefined,
    patchStatus: "patched",
    summary:
      "Third Firefox 150 use-after-free credited to Mythos in MFSA 2026-30. Public CVE issued because the bug was reachable from sandboxed web content.",
    source: { label: "MFSA 2026-30", url: "https://www.mozilla.org/en-US/security/advisories/" },
  },
  {
    id: "CVE-2026-28952",
    vendor: "Apple",
    product: "macOS 26.4.1 / Apple M5 silicon",
    component: "XNU kernel",
    vulnType: "Local privilege escalation (MIE bypass)",
    severity: "high",
    discoveryMethod: "mythos",
    discoveryCredit: "Bruce Dang, Dion Blazakis, Josh Maine (Calif) using Claude Mythos",
    disclosedAt: "2026-05-14",
    patchedAt: "2026-05-19",
    glasswingPartner: "Apple",
    patchStatus: "patched",
    summary:
      "Two macOS kernel bugs chained into a working local privilege escalation that bypassed Memory Integrity Enforcement (MIE), the hardware mitigation Apple spent five years building. Bugs found 25 Apr, exploit running 1 May, disclosed to Apple in Cupertino. macOS Tahoe 26.5 credits Calif and Anthropic Research.",
    source: { label: "Hacker News thread", url: "https://news.ycombinator.com/item?id=48273169" },
  },
  {
    id: "MYTHOS-OPENBSD-SACK",
    vendor: "OpenBSD",
    product: "OpenBSD kernel",
    component: "TCP SACK implementation",
    vulnType: "Integer overflow (remote DoS)",
    severity: "high",
    discoveryMethod: "mythos",
    discoveryCredit: "Anthropic Mythos Preview team",
    disclosedAt: "2026-04-07",
    patchedAt: "2026-04-15",
    ageYears: 27,
    glasswingPartner: undefined,
    patchStatus: "patched",
    summary:
      "27-year-old integer overflow in OpenBSD TCP SACK handling. Remote attacker can crash any OpenBSD host responding over TCP. No public CVE assigned at disclosure - tracked in OpenBSD errata.",
    source: { label: "Claude Mythos Preview", url: "https://red.anthropic.com/2026/mythos-preview/" },
    notes: "No CVE-ID assigned at disclosure; vendor errata only.",
  },
  {
    id: "MYTHOS-FFMPEG-16YR",
    vendor: "FFmpeg",
    product: "FFmpeg",
    vulnType: "Memory corruption (codec parser)",
    severity: "medium",
    discoveryMethod: "mythos",
    discoveryCredit: "Anthropic Mythos Preview team",
    disclosedAt: "2026-04-07",
    glasswingPartner: undefined,
    patchStatus: "in-disclosure",
    ageYears: 16,
    summary:
      "16-year-old memory corruption in an FFmpeg codec parser, surfaced in the original Mythos disclosure. Vendor patch is in coordinated disclosure as of the Glasswing rollout window.",
    source: { label: "Claude Mythos Preview", url: "https://red.anthropic.com/2026/mythos-preview/" },
  },
  {
    id: "CVE-2025-9478",
    vendor: "Google",
    product: "Chrome",
    component: "ANGLE graphics library",
    vulnType: "Use-after-free",
    severity: "high",
    discoveryMethod: "big-sleep",
    discoveryCredit: "Google DeepMind / Project Zero - Big Sleep agent",
    disclosedAt: "2025-08-11",
    patchedAt: "2025-08-19",
    glasswingPartner: "Google",
    patchStatus: "patched",
    summary:
      "First public real-world security vulnerability caught by an AI agent (Big Sleep) before exploitation. Use-after-free in Chrome's ANGLE graphics library, verified by human researchers and patched within eight days.",
    source: { label: "SecurityWeek - Big Sleep", url: "https://www.securityweek.com/google-detects-first-ai-generated-zero-day-exploit/" },
    notes: "Pre-Mythos but the anchor case for AI-discovered CVE tracking.",
  },
  {
    id: "MYTHOS-LINUX-NDAY-CLUSTER",
    vendor: "Linux Foundation",
    product: "Linux kernel",
    vulnType: "N-day privilege escalation (cluster)",
    severity: "high",
    discoveryMethod: "mythos",
    discoveryCredit: "Anthropic Mythos Preview team",
    disclosedAt: "2026-04-07",
    glasswingPartner: "Linux Foundation",
    patchStatus: "patched",
    summary:
      "Demonstration set: Mythos was given 100 Linux kernel CVEs from 2024-2025, filtered to 40 exploitable candidates and built working privilege-escalation exploits for more than half. Glasswing partners received the exploit code; public reporting redacts CVE IDs.",
    source: { label: "Help Net Security", url: "https://www.helpnetsecurity.com/2026/04/08/anthropic-claude-mythos-preview-identify-vulnerabilities/" },
    notes: "Aggregate finding - individual CVE IDs withheld pending Glasswing rollout.",
  },
];

export const AGGREGATE_STATS = {
  mythosFirefoxFindings: 271,
  firefoxPublicCvesFromMythos: 3,
  mozillaTotalAprilFixes: 423,
  mozillaExternalReports: 41,
  mozillaInternal: 111,
  glasswingPartners: [
    "AWS",
    "Apple",
    "Broadcom",
    "Cisco",
    "CrowdStrike",
    "Google",
    "JPMorgan Chase",
    "Linux Foundation",
    "Microsoft",
    "NVIDIA",
    "Palo Alto Networks",
  ],
  glasswingCredits: "$100M usage credits for defenders",
};

export const VENDORS = Array.from(new Set(CVES.map((c) => c.vendor))).sort();
